### ISSUE TITLE
Framework Crashes if Sections Supplementary Views are Added

### ISSUE THREAD

**Issue by azamsharp** [mokagio/UICollectionViewLeftAlignedLayout#16]
The framework crashes if supplemenatary footer views are added.

**Comment by topLayoutGuide** [comment]
This is a long time coming @azamsharp but this issue has been fixed in later releases. Specifically 1.0.3 (Swift 4) fixes it. I didn't update the Objective-C variant yet, however. So the issue may still lie within it.

I'll close this issue now, but feel free to reopen it in future if the issue still occurs. 👍
